### PR TITLE
fix: Ensure latest user api keys are fetched on profile page

### LINKED ISSUE #9848: [BUG] Unhandled undefined on /profile
Error on /profile, fixed itself on reload

Image

Image

Image

### PR DESCRIPTION
**Pull request by cephalization**
Also guard against cases where api key edge members may be undefined. This happens in hard to reproduce edge-cases.

Resolves #9848

---

> [!NOTE]
> Profile now refetches the viewer to get up-to-date API keys; mutation returns `viewer` and table filters undefined entries.
> 
> - **Profile/Viewer**:
>   - Call `refetchViewer()` on mount in `pages/profile/ProfilePage.tsx` to fetch latest `viewer`/API keys.
>   - Stabilize `refetchViewer` in `contexts/ViewerContext.tsx` with `useCallback`.
> - **API Keys Table**:
>   - Update delete mutation to return `query.viewer { ...APIKeysTableFragment }` and align generated Relay types.
>   - Change post-delete refetch policy to `store-and-network`.
>   - Guard table data by filtering `data.apiKeys` to remove undefined entries.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 82858be14d3c8c6555d427e784ed9f3a8ba82586. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: app/src/pages/profile/APIKeysTable.tsx [hunk 1]
```diff
@@ -69,7 +69,7 @@ export function APIKeysTable({ query }: { query: APIKeysTableFragment$key }) {
             refetch(
               {},
               {
-                fetchPolicy: "network-only",
+                fetchPolicy: "store-and-network",
```
Comment (yfrigui2) [inline app/src/pages/profile/APIKeysTable.tsx:72]: just wondering, why store-and-network here?

Comment (cephalization) [reply app/src/pages/profile/APIKeysTable.tsx:72]: It prevents flicker by leaving the old results in place until the new ones are loaded. With network only you instantly nuke all rows and then fetch new ones
