### PR TITLE
fix(ui): broken popovers

### LINKED ISSUE #6829: [BUG]:  cannot create or add to dataset
### Where do you use Phoenix

Local (self-hosted)

### What version of Phoenix are you using?

*

### What operating system are you seeing the problem on?

*

### What version of Python are you running Phoenix with?

 * 

### What version of Python or Node are you using instrumentation with?

*

### What instrumentation are you using?

*

### What happened?

UI is fully broken

### What did you expect to happen?

*

### How can we reproduce the bug?

*

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by mikeldking**
resolves #6829 

Most likely caused by react-aria changing the even propagation on buttons.

### CODE REVIEW

File: app/src/contexts/ThemeContext.tsx [hunk 1]
```diff
@@ -53,6 +53,14 @@ export function ThemeProvider(
     }
   }, [props.theme, setTheme]);
 
+  useEffect(() => {
+    // When the theme changes, set a class on the body to override the default theme
+    document.body.classList.add(`ac-theme--${theme}`);
```
Comment (mikeldking) [inline app/src/contexts/ThemeContext.tsx:58]: the portals were not getting the themes so pushing it up to the body

**Review by cephalization — APPROVED** [review]
