### PR TITLE
fix(prompts): rename google provider

### LINKED ISSUE #6400: Switch from Gemini to Google for provider enum
Google is more semantic and how it's used in the wild

### PR DESCRIPTION
**Pull request by axiomofjoy**
resolves #6400

### CODE REVIEW

**Review by RogerHYang — APPROVED** [review]

File: app/src/pages/playground/constants.tsx [hunk 1]
```diff
@@ -39,7 +39,7 @@ export const modelProviderToModelPrefixMap: Record<ModelProvider, string[]> = {
   AZURE_OPENAI: [],
   ANTHROPIC: ["claude"],
   OPENAI: ["gpt", "o1"],
-  GEMINI: ["gemini"],
+  GOOGLE: ["gemini"],
```
Comment (mikeldking) [inline app/src/pages/playground/constants.tsx:42]: Is this right? Looking now

Comment (mikeldking) [reply app/src/pages/playground/constants.tsx:42]: nvm

**Review by cephalization — APPROVED** [review]
