### PR TITLE
fix: Remove deadzone when hovering example table cells

### LINKED ISSUE #5554: [BUG] UI shows scrollbars on some cells
Screenshot 2024-11-26 at 12 03 03 PM

### PR DESCRIPTION
**Pull request by cephalization**
There was a deadzone on the control hovering styles caused by padding in the parent td element.
Now cell contents control their own padding, and fill available td space, so that the hover target matches the visible cell area.

### After

Resolves #5554

### CODE REVIEW

File: app/src/pages/playground/PlaygroundDatasetExamplesTable.tsx [hunk 1]
```diff
@@ -411,6 +413,8 @@ function TableBody<T>({ table }: { table: Table<T> }) {
               <td
                 key={cell.id}
                 style={{
+                  padding: 0,
+                  height: 1,
```
Comment (cephalization) [inline app/src/pages/playground/PlaygroundDatasetExamplesTable.tsx:417]: The cell still grows to fit, we just need _some_ height declared so that `height: 100%` in the children works

Comment (Parker-Stafford) [reply app/src/pages/playground/PlaygroundDatasetExamplesTable.tsx:417]: Can you put a comment to that effect?

**Review by Parker-Stafford — APPROVED** [review]
