### PR TITLE
fix(playground): fix pagination on playground dataset examples table

### LINKED ISSUE #5382: [playground][ui] cannot paginate datasets table on playground page

### PR DESCRIPTION
**Pull request by Parker-Stafford**
resolves #5382 

- fixes pagination on dataset examples table on playground
- reduces initial and subsequent page sizes
- adds button to navigate to playground from dataset

pagination:

https://github.com/user-attachments/assets/a16bef47-afc0-4e71-91f6-ee4eb0376b95

dataset -> playground nav:

https://github.com/user-attachments/assets/3a871557-0b32-462b-a031-870225e20191

### CODE REVIEW

File: app/src/pages/playground/PlaygroundDatasetExamplesTable.tsx [hunk 1]
```diff
@@ -78,7 +78,7 @@ import {
 } from "./PlaygroundToolCall";
 import { getChatCompletionOverDatasetInput } from "./playgroundUtils";
 
-const PAGE_SIZE = 100;
+const PAGE_SIZE = 10;
```
Comment (cephalization) [inline app/src/pages/playground/PlaygroundDatasetExamplesTable.tsx:81]: Should this match the 20 defined in the query below?

**Review by cephalization — APPROVED** [review]

File: app/src/pages/playground/PlaygroundDatasetExamplesTable.tsx (hunk 1 above)
Comment (Parker-Stafford) [reply app/src/pages/playground/PlaygroundDatasetExamplesTable.tsx:81]: it doesn't need to, fetch 20 initially then 10 for each page. Doesn't make a big difference either way
