### PR TITLE
fix: make users table scrollable

### LINKED ISSUE #10315: [bug] admin users table is not paginated

### PR DESCRIPTION
**Pull request by axiomofjoy**
https://github.com/user-attachments/assets/1bd1c410-5fb9-4f34-abc7-d104e374e932

resolves #10315

### CODE REVIEW

File: app/src/pages/settings/UsersCard.tsx [hunk 1]
```diff
@@ -66,17 +66,15 @@ export function UsersCard() {
         </Button>
       }
     >
-      <View overflow="auto">
```
Comment (axiomofjoy) [inline app/src/pages/settings/UsersCard.tsx:69]: Scrollable container moved into `UsersTable` component.

File: app/src/pages/settings/UserRoleChangeDialog.tsx [hunk 2]
```diff
@@ -22,21 +22,25 @@ export function UserRoleChangeDialog({
...
       mutation UserRoleChangeDialogMutation($input: PatchUserInput!) {
         patchUser(input: $input) {
-          __typename
+          user {
+            id
+            role {
+              id
+              name
+            }
+          }
```
Comment (axiomofjoy) [inline app/src/pages/settings/UserRoleChangeDialog.tsx:43]: Spread to update. Maybe this should be an inline fragment?

Comment (axiomofjoy) [reply app/src/pages/settings/UserRoleChangeDialog.tsx:43]: cc @cephalization
