### PR TITLE
fix(playground): add tooltip for dataset examples

### LINKED ISSUE #5353: [playground][ui] use tooltip for dataset example slideover

### PR DESCRIPTION
**Pull request by axiomofjoy**
https://github.com/user-attachments/assets/f2e05d58-e0a9-4d96-9549-8918e726088a

resolves #5353

### CODE REVIEW

File: app/src/pages/playground/PlaygroundDatasetExamplesTable.tsx [hunk 1]
```diff
@@ -831,9 +844,9 @@ export function PlaygroundDatasetExamplesTable({
         {isEmpty ? (
           <TableEmpty />
         ) : table.getState().columnSizingInfo.isResizingColumn ? (
-          <MemoizedTableBody table={table} datasetId={datasetId} />
+          <MemoizedTableBody table={table} />
         ) : (
-          <TableBody table={table} datasetId={datasetId} />
+          <TableBody table={table} />
```
Comment (cephalization) [inline app/src/pages/playground/PlaygroundDatasetExamplesTable.tsx:849]: Is there a reason why we are no longer using MemoizedTableBody?

**Review by cephalization — APPROVED** [review]
