### PR TITLE
fix(perf): disable streaming when dialog is open

### LINKED ISSUE #6935: [bug] (perf) streaming doesn't stop when you have a slideover open

### PR DESCRIPTION
**Pull request by mikeldking**
resolves #6935

This disables streaming when there's a dialog open since it's not necessary to keep polling the backend for more traces.

### CODE REVIEW

File: app/src/pages/project/StreamToggle.tsx [hunk 1]
```diff
@@ -13,8 +14,24 @@ import { StreamToggle_data$key } from "./__generated__/StreamToggle_data.graphql
  */
 const REFRESH_INTERVAL_MS = 2000;
 
+/**
+ * Routes where streaming is enabled
+ */
+const STREAMING_ENABLED_ROUTES = ["/spans", "/traces", "/sessions"];
```
Comment (cephalization) [inline app/src/pages/project/StreamToggle.tsx:20]: `STREAMING_ENABLED_ROUTE_TAILS`? This took me a minute to realize that only if the path ends with one of these streaming will be enabled.

**Review by cephalization — APPROVED** [review]

File: app/src/pages/project/StreamToggle.tsx (hunk 1 above)
Comment (mikeldking) [reply app/src/pages/project/StreamToggle.tsx:20]: makes sense
