### PR TITLE
fix(auth): allow login form scroll

### LINKED ISSUE #5365: [auth][ui] allow login scroll
This is a stop gap for https://github.com/Arize-ai/phoenix/issues/5367

### PR DESCRIPTION
**Pull request by axiomofjoy**
https://github.com/user-attachments/assets/44f17fee-e584-495e-a5c4-fa58a604251d

resolves #5365

### CODE REVIEW

File: app/src/pages/auth/AuthLayout.tsx [hunk 1]
```diff
@@ -31,6 +31,7 @@ export function AuthLayout({ children }: PropsWithChildren) {
         marginStart="auto"
         marginEnd="auto"
         borderRadius="medium"
+        overflow={"auto"}
```
Comment (cephalization) [inline app/src/pages/auth/AuthLayout.tsx:34]: Tiny nit

```suggestion
        overflow="auto"
```

**Review by cephalization — APPROVED** [review]
