### PR TITLE
fix: long project names do not overflow and squash project icon

### LINKED ISSUE #2565: [BUG] launch_app fails in AWS SageMaker JupyterLab
**Describe the bug**
Running code from AWS SageMaker Notebook fails with "Unexpected token 'M', "Method Not Allowed" is not valid JSON" on the dynamic url create ( https://genaiworkshop1.notebook.us-east-1.sagemaker.aws/proxy/6006/). 

This is basically the sample code from the Phoenix Arize examples. This exact code works fine in Google Colab. 

**Screenshots**

Screen Shot 2024-03-13 at 6 21 07 PM

Screen Shot 2024-03-13 at 6 21 26 PM

**Code that fails**
'''
px.close_app()
session = px.launch_app()
LangChainInstrumentor().instrument()
'''

### LINKED ISSUE #2656: [BUG] Fix flexbox and long titles on project listing.

### PR DESCRIPTION
**Pull request by axiomofjoy**
resolves #2656 

Before:

Screenshot 2024-03-23 at 9 29 59 PM

After:

Screenshot 2024-03-23 at 9 29 25 PM

[relevant article](https://www.bigbinary.com/blog/understanding-the-automatic-minimum-size-of-flex-items)

### CODE REVIEW

File: app/src/pages/projects/ProjectsPage.tsx [hunk 1]
```diff
@@ -167,10 +168,19 @@ function ProjectItem({
       `}
     >
       <Flex direction="row" justifyContent="space-between" alignItems="start">
-        <Flex direction="row" gap="size-100" alignItems="center">
+        <Flex direction="row" gap="size-100" alignItems="center" minWidth={0}>
```
Comment (mikeldking) [inline app/src/pages/projects/ProjectsPage.tsx:171]: What does the minority do?

**Review by mikeldking — APPROVED** [review]
