### PR TITLE
fix(promts): load invocation parameters for azure openai

### LINKED ISSUE #6365: [prompts] Azure OpenAI prompt doesn't re-hydrate invocation back into the playground

### PR DESCRIPTION
**Pull request by mikeldking**
resolves #6365 

This restores the ability to load in an azure openai prompt. It also makes the version a combobox.

### CODE REVIEW

File: app/src/pages/playground/fetchPlaygroundPrompt.ts [hunk 1]
```diff
@@ -594,9 +587,7 @@ export const fetchPlaygroundPromptAsInstance = async (
     const supportedInvocationParameters =
       await fetchSupportedInvocationParameters({
         modelName: latestPromptVersion.modelName,
-        providerKey: openInferenceModelProviderToPhoenixModelProvider(
-          latestPromptVersion.modelProvider
-        ),
+        providerKey: latestPromptVersion.modelProvider,
```
Comment (mikeldking) [inline app/src/pages/playground/fetchPlaygroundPrompt.ts:590]: this is the bug

**Review by cephalization — APPROVED** [review]
