### PR TITLE
feat: ability to clear data older than X date, fix DB constraint errors for span.id from datasets to projects

### LINKED ISSUE #3641: [ENHANCEMENT] Allow users to clear traces older than X days old
For retention needs, let users clear traces before X number of days

### LINKED ISSUE #3671: [BUG] Foreign Key contraint issue when removing traces from a project
Fails to clear traces from a project if there is a foreign key.

### PR DESCRIPTION
**Pull request by mikeldking**
resolves #3671
resolves #3641 

Adds the ability to clear traces older than X for a given project. Also fixes DB constraint errors that were introduced that caused clear traces to fail.
Screenshot 2024-06-26 at 8 30 52 AM

### CODE REVIEW

File: app/src/components/dataset/CreateDatasetForm.tsx [hunk 1]
```diff
@@ -75,70 +75,68 @@ export function CreateDatasetForm(props: CreateDatasetFormProps) {
...
-              size="compact"
-              loading={isCommitting}
-            >
-              {isCommitting ? "Creating..." : "Create Dataset"}
-            </Button>
-          </Flex>
-        </View>
-      </Form>
-    </>
+    <Form onSubmit={handleSubmit(onSubmit)}>
```
Comment (mikeldking) [inline app/src/components/dataset/CreateDatasetForm.tsx:78]: just removing the fragment

File: src/phoenix/server/api/mutations/project_mutations.py [hunk 2]
```diff
@@ -32,11 +33,20 @@ async def delete_project(self, info: Info[Context, None], id: GlobalID) -> Query
...
         async with info.context.db() as session:
-            await session.execute(delete_statement)
+            try:
+                await session.execute(delete_statement)
+                await session.commit()
+            except Exception:
+                await session.rollback()
+                raise
             if cache := info.context.cache_for_dataloaders:
                 cache.invalidate(ClearProjectSpansEvent(project_rowid=project_id))
```
Comment (RogerHYang) [inline src/phoenix/server/api/mutations/project_mutations.py:51]: rollback/commit is automatic. the erroneous portion is actually the placement of the invalidate statement
```suggestion
            await session.execute(delete_statement)
        if cache := info.context.cache_for_dataloaders:
            cache.invalidate(ClearProjectSpansEvent(project_rowid=project_id))
```

File: src/phoenix/server/api/input_types/ClearProjectInput.py [hunk 3]
```diff
@@ -0,0 +1,12 @@
...
+
+import strawberry
+from strawberry import UNSET
+from strawberry.relay import GlobalID
+
+
+@strawberry.input
+class ClearProjectInput:
+    id: GlobalID
+    end_time: Optional[datetime] = UNSET
```
Comment (RogerHYang) [inline src/phoenix/server/api/input_types/ClearProjectInput.py:12]: maybe add quick note to eliminate any ambiguity about which side of the cutoff is being deleted (even though one side makes more sense than the other)

**Review by RogerHYang — APPROVED** [review]

File: app/src/pages/RemoveProjectDataForm.tsx [hunk 4]
```diff
@@ -0,0 +1,129 @@
...
+        },
+      });
+    },
+    [commit, projectId, props, setError]
+  );
+  return (
+    <form onSubmit={handleSubmit(onSubmit)} ref={formRef}>
+      <View padding="size-200">
+        <Text color="danger">
+          {`You are about to remove data up to the following date. This cannot be undone.`}
```
Comment (RogerHYang) [inline app/src/pages/RemoveProjectDataForm.tsx:77]: maybe before is less ambiguous
```suggestion
          {`You are about to remove data before the following date. This cannot be undone.`}
```

Comment (mikeldking) [reply app/src/pages/RemoveProjectDataForm.tsx:77]: I changed it to data since it will delete evals too. Will adjust.

File: src/phoenix/db/models.py [hunk 5]
```diff
@@ -483,7 +483,7 @@ class DatasetExample(Base):
         index=True,
     )
     span_rowid: Mapped[Optional[int]] = mapped_column(
-        ForeignKey("spans.id"),
+        ForeignKey("spans.id", ondelete="SET NULL"),
```
Comment (axiomofjoy) [inline src/phoenix/db/models.py:486]: Good catch.
