### PR TITLE
fix(playground): ensure playground repetition status is cleared

### LINKED ISSUE #10350: [bug] playground loading spinner runs unnecessarily
When switching from playground single manual input mode after running an experiment over a dataset, the loading spinner is still going.

### PR DESCRIPTION
**Pull request by axiomofjoy**
resolves #10350

---

> [!NOTE]
> Ensure all repetitions are marked finished when canceling or completing, remove unused instance-level span clearing, and add targeted tests.
> 
> - **Store (`app/src/store/playground/playgroundStore.tsx`)**:
>   - `markPlaygroundInstanceComplete`: also sets all `repetitions[*].status` to `"finished"` and clears `activeRunId`.
>   - `cancelPlaygroundInstances`: sets all `repetitions[*].status` to `"finished"` and clears `activeRunId`.
>   - `runPlaygroundInstances`: initializes repetitions fresh without clearing an instance-level `spanId` field.
> - **Tests (`app/src/store/playground/__tests__/playgroundStore.test.ts`)**:
>   - Add coverage for `markPlaygroundInstanceComplete` (only target instance affected; all reps finished).
>   - Add coverage for `cancelPlaygroundInstances` (all instances; all reps finished).
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 0e0dddde13192361118433b2f0426dbe1af1a7be. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

**Review by cephalization — APPROVED** [review]

File: app/src/store/playground/playgroundStore.tsx [hunk 1]
```diff
@@ -799,6 +799,21 @@ export const createPlaygroundStore = (props: InitialPlaygroundState) => {
               return {
                 ...instance,
                 activeRunId: null,
+                repetitions: Object.fromEntries(
```
Comment (mikeldking) [inline app/src/store/playground/playgroundStore.tsx:800]: we should probably start putting some tests in.

Comment (axiomofjoy) [reply app/src/store/playground/playgroundStore.tsx:800]: Added.
