### PR TITLE
fix(playground): plumb through and record invocation parameters

### LINKED ISSUE #4990: [playground][gql] invocation parameter input

### PR DESCRIPTION
**Pull request by axiomofjoy**
- plumbs invocation parameters through the GraphQL layer
- records invocation parameters on the resulting span

```graphql
subscription ChatCompletionSubscription($messages: [ChatCompletionMessageInput!]!, $model: GenerativeModelInput!, $invocationParameters: InvocationParameters!) {
  chatCompletion(
    input: {messages: $messages, model: $model, invocationParameters: $invocationParameters}
  )
}
```

Screenshot 2024-10-14 at 8 33 57 PM

Screenshot 2024-10-14 at 8 34 03 PM

resolves #4990

### CODE REVIEW

**Comment by axiomofjoy** [comment]
Pulled back into draft

File: app/src/pages/playground/PlaygroundOutput.tsx [hunk 1]
```diff
@@ -187,6 +193,9 @@ function PlaygroundOutputText(props: PlaygroundInstanceProps) {
         providerKey: instance.model.provider,
         name: instance.model.modelName || "",
       },
+      invocationParameters: {
+        temperature: 0.1, // TODO: add invocation parameters
+      },
```
Comment (mikeldking) [inline app/src/pages/playground/PlaygroundOutput.tsx:198]: should we start with 0.0?

**Review by mikeldking — APPROVED** [review]

File: app/src/pages/playground/PlaygroundOutput.tsx (hunk 1 above)
Comment (axiomofjoy) [reply app/src/pages/playground/PlaygroundOutput.tsx:198]: No temperature needs to be hard-coded in the frontend. I just have this here so I can test to make sure the invocation parameters are showing up in the instrumented LLM spans, but we will erase once we have some UI around it.
