### PR TITLE
fix: De-duplicate dialog code in model delete dialog

### LINKED ISSUE #8159: [cost][ui] delete model modal collapses
Image

### PR DESCRIPTION
**Pull request by cephalization**
image

Resolves #8159

## Summary by Sourcery

Deduplicate the model deletion dialog by removing the custom <Dialog> wrapper and header markup in DeleteModelButton and replacing it with a generic container

Enhancements:
- Extract common deletion dialog structure to avoid repeating <Dialog> elements
- Replace <Dialog> component with a standard <div> wrapper in DeleteModelDialogContent

### CODE REVIEW

File: app/src/pages/settings/DeleteModelButton.tsx [hunk 1]
```diff
@@ -82,13 +82,7 @@ function DeleteModelDialogContent({
...
 
   return (
-    <Dialog>
-      <DialogHeader>
-        <DialogTitle>Delete Model</DialogTitle>
-        <DialogTitleExtra>
-          <DialogCloseButton slot="close" />
-        </DialogTitleExtra>
-      </DialogHeader>
+    <div>
```
Comment (mikeldking) [inline app/src/pages/settings/DeleteModelButton.tsx:85]: div not needed?

Comment (cephalization) [reply app/src/pages/settings/DeleteModelButton.tsx:85]: Suppose not, a fragment should work
