### PR TITLE
fix: use correlated subquery for orphan spans

### LINKED ISSUE #6897: change left outer join to correlated subquery when filtering for orphaned spans
A user reported that the left outer join can have significant performance issues when data is very large, but the correlated subquery has worked fine.

### PR DESCRIPTION
**Pull request by RogerHYang**
resolves #6897 

This PR implements Query 4 (from below) for Phoenix.

# Query Performance Comparison (PostgreSQL)

| Query #    | Median (ms)  | Ratio    | P90 (ms)   | N Runs   | Rows Returned |
|------------|-------------:|---------:|-----------:|---------:|--------------:|
| Query 1    |         37.0 |     1.00 |       51.4 |       20 |          1000 |
| Query 2    |        429.1 |    11.61 |      459.9 |       20 |          1000 |
| Query 3    |        447.1 |    12.10 |      497.8 |       20 |          1000 |
| Query 4    |        435.9 |    11.80 |      468.3 |       20 |          1000 |
| Query 5    |       5941.8 |   160.81 |     6640.5 |       20 |          1000 |
| Query 6    |        858.2 |    23.23 |      916.0 |       20 |          1000 |
| Query 7    |        380.5 |    10.30 |      399.2 |       20 |          1000 |

### Generated Data (with no attributes)
traces: 3,935
spans: 2,599,383

# Tested Queries (PostgreSQL)

```sql
-- Query 1
-- Root span only; no orphan spans
SELECT spans.id,
       spans.start_time AS "startTime_span_sort_column"
FROM spans
         JOIN
     traces ON traces.id = spans.trace_rowid
WHERE traces.project_rowid = 9
  AND spans.start_time >= (NOW() - INTERVAL '2000 hours')
  AND spans.parent_id IS NULL
ORDER BY "startTime_span_sort_column" DESC NULLS LAST,
         spans.id DESC
LIMIT 1000;

-- Query 2
-- Left outer join
SELECT spans.id,
       spans.start_time AS "startTime_span_sort_column"
FROM spans
         JOIN
     traces ON traces.id = spans.trace_rowid
         LEFT OUTER JOIN (SELECT span_id
                          FROM spans) AS parent ON spans.parent_id = parent.span_id
WHERE traces.project_rowid = 9
  AND spans.start_time >= (NOW() - INTERVAL '2000 hours')
  AND parent.span_id IS NULL
ORDER BY "startTime_span_sort_column" DESC NULLS LAST,
         spans.id DESC
LIMIT 1000;

-- Query 3
-- Left outer join with OR clause
SELECT spans.id,
       spans.start_time AS "startTime_span_sort_column"
FROM spans
         JOIN
     traces ON traces.id = spans.trace_rowid
         LEFT OUTER JOIN (SELECT span_id
                          FROM spans) AS parent ON spans.parent_id = parent.span_id
WHERE traces.project_rowid = 9
  AND spans.start_time >= (NOW() - INTERVAL '2000 hours')
  AND (spans.parent_id IS NULL OR parent.span_id IS NULL)
ORDER BY "startTime_span_sort_column" DESC NULLS LAST,
         spans.id DESC
LIMIT 1000;

-- Query 4
-- Correlated subquery
SELECT spans.id,
       spans.start_time AS "startTime_span_sort_column"
FROM spans
         JOIN
     traces ON traces.id = spans.trace_rowid
WHERE traces.project_rowid = 9
  AND spans.start_time >= (NOW() - INTERVAL '2000 hours')
  AND NOT EXISTS (SELECT 1
                  FROM spans parent
                  WHERE spans.parent_id = parent.span_id)
ORDER BY "startTime_span_sort_column" DESC NULLS LAST,
         spans.id DESC
LIMIT 1000;

-- Query 5
-- Correlated subquery with OR clause
SELECT spans.id,
       spans.start_time AS "startTime_span_sort_column"
FROM spans
         JOIN
     traces ON traces.id = spans.trace_rowid
WHERE traces.project_rowid = 9
  AND spans.start_time >= (NOW() - INTERVAL '2000 hours')
  AND (spans.parent_id IS NULL OR NOT EXISTS (SELECT 1
                                              FROM spans parent
                                              WHERE spans.parent_id = parent.span_id))
ORDER BY "startTime_span_sort_column" DESC NULLS LAST,
         spans.id DESC
LIMIT 1000;

-- Query 6
-- Correlated subquery with CTE
WITH candidate_spans AS (SELECT spans.id,
                                spans.parent_id,
                                spans.start_time AS "startTime_span_sort_column"
                         FROM spans
                                  JOIN
                              traces ON traces.id = spans.trace_rowid
                         WHERE traces.project_rowid = 9
                           AND spans.start_time >= (NOW() - INTERVAL '2000 hours')
                         ORDER BY "startTime_span_sort_column" DESC NULLS LAST,
                                  id DESC)
SELECT id,
       "startTime_span_sort_column"
FROM candidate_spans c
WHERE NOT EXISTS (SELECT 1
                  FROM spans s
                  WHERE s.span_id = c.parent_id)
LIMIT 1000;

-- Query 7
-- Correlated subquery with CTE with OR clause
WITH candidate_spans AS (SELECT spans.id,
                                spans.parent_id,
                                spans.start_time AS "startTime_span_sort_column"
                         FROM spans
                                  JOIN
                              traces ON traces.id = spans.trace_rowid
                         WHERE traces.project_rowid = 9
                           AND spans.start_time >= (NOW() - INTERVAL '2000 hours')
                         ORDER BY "startTime_span_sort_column" DESC NULLS LAST,
                                  id DESC)
SELECT id,
       "startTime_span_sort_column"
FROM candidate_spans c
WHERE parent_id IS NULL
   OR NOT EXISTS (SELECT 1
                  FROM spans s
                  WHERE s.span_id = c.parent_id)
LIMIT 1000;
```

### CODE REVIEW

File: scripts/perf/postgres/paste_queries_here.sql [hunk 1]
```diff
@@ -0,0 +1,8 @@
+-- PostgreSQL Query Runtime Summarizer
+-- Paste your SQL queries below, separated by semicolons (;)
+-- Comments starting with -- will be ignored
+--
+-- Example:
+-- SELECT * FROM spans ORDER BY id LIMIT 100;
+-- SELECT COUNT(*) FROM spans;
+--
```
Comment (mikeldking) [inline scripts/perf/postgres/paste_queries_here.sql:8]: Did you mean to check this in?

File: app/schema.graphql [hunk 2]
```diff
@@ -1390,7 +1390,7 @@ type Project implements Node {
   latencyMsQuantile(probability: Float!, timeRange: TimeRange): Float
   spanLatencyMsQuantile(probability: Float!, timeRange: TimeRange, filterCondition: String): Float
   trace(traceId: ID!): Trace
-  spans(timeRange: TimeRange, first: Int = 30, last: Int, after: String, before: String, sort: SpanSort, rootSpansOnly: Boolean, filterCondition: String): SpanConnection!
+  spans(timeRange: TimeRange, first: Int = 30, last: Int, after: String, before: String, sort: SpanSort, rootSpansOnly: Boolean, filterCondition: String, orphanSpanAsRootSpan: Boolean = true): SpanConnection!
```
Comment (mikeldking) [inline app/schema.graphql:1393]: should we default this to be false and see if people complain?

File: scripts/perf/postgres/paste_queries_here.sql (hunk 1 above)
Comment (RogerHYang) [reply scripts/perf/postgres/paste_queries_here.sql:8]: yea, it's a placeholder file for future queries

**Review by mikeldking — APPROVED** [review]

File: app/schema.graphql (hunk 2 above)
Comment (RogerHYang) [reply app/schema.graphql:1393]: maybe we should let the people who want more performance complain instead?
