### PR TITLE
fix(playground): fix dataset picker styles and error handling

### LINKED ISSUE #5327: [playground][ui] datasets subscription cleanup
- [x] improve error handling per cell
- [x] figure out updates during transition
- [x] clear experimentId on run
- [x] column sizing fixes
  - [x] fix effect deps
  - [x] fix weird resizing

### PR DESCRIPTION
**Pull request by Parker-Stafford**
resolves #5327 

- fixes error handling for playground on dataset
image

- fixes dataset picker and clear button styles to be the same height
- fixes issue where playground project was no longer being returned
- fixes console warning about updates in a transition by removing transition when selecting a dataset and adding suspense and loader

### CODE REVIEW

File: app/src/pages/playground/PlaygroundDatasetPicker.tsx [hunk 1]
```diff
@@ -1,22 +1,33 @@
...
 
 import { DatasetPicker } from "@phoenix/components/dataset";
 import { usePlaygroundContext } from "@phoenix/contexts/PlaygroundContext";
 
+/**
+ * This is to keep the height of the picker and the button the same
+ * Our buttons have icons with size of 1.3rem, which becomes 20.8px where as the picker text has a line height of 20px with border and margins this becomes 30px
+ * so the height of the picker does not change , we just shrink the button a bit to match the height of the picker
+ * This is currently the case everywhere, where a compact button with an icon will be .8px bigger than a compact button without
+ */
```
Comment (cephalization) [inline app/src/pages/playground/PlaygroundDatasetPicker.tsx:14]: Nice, I was going to point this out today too

File: src/phoenix/server/api/queries.py [hunk 2]
```diff
@@ -235,15 +236,17 @@ async def projects(
...
+                    ~exists().where(models.Experiment.project_name == models.Project.name),
+                    models.Project.name == PLAYGROUND_PROJECT_NAME,
+                )
             )
-            .where(models.Experiment.project_name.is_(None))
             .order_by(models.Project.id)
         )
         async with info.context.db() as session:
             projects = await session.stream_scalars(stmt)
+            print("test--", projects)
```
Comment (cephalization) [inline src/phoenix/server/api/queries.py:249]:
```suggestion
```

**Review by cephalization — APPROVED** [review]
