### PR TITLE
fix: Bubble errors up from nested invocation parameter schema transforms

### LINKED ISSUE #5198: [BUG] invocation parameter parsing from a span to playground does not properly surface parsing errors
**Describe the bug**
When the invocation parameters are unparsable (via zod or json parse) the error is not surfaced up to the playground leading to lossy information without the user knowing

Here are some tests to reproduce the issue
This one will return the following for invocation parameters
```
[
  {
    "code": "invalid_type",
    "expected": "object",
    "received": "string",
    "path": [],
    "message": "Expected object, received string"
  }
]
```
```typescript
 it("should return invocation parameters parsing errors if they are malformed", () => {
    const parsedAttributes = {
      llm: {
        model_name: "gpt-3.5-turbo",
        invocation_parameters: '"invalid"',
      },
    };
    expect(getModelConfigFromAttributes(parsedAttributes)).toEqual({
      modelConfig: {
        modelName: "gpt-3.5-turbo",
        provider: "OPENAI",
        invocationParameters: {},
      },
      parsingErrors: [MODEL_CONFIG_WITH_INVOCATION_PARAMETERS_PARSING_ERROR],
    });
  });
```

this one will just not have any parsing errors since the json is invalid
```typescript
 it("should return invocation parameters parsing errors if they are malformed", () => {
    const parsedAttributes = {
      llm: {
        model_name: "gpt-3.5-turbo",
        invocation_parameters: "invalid",
      },
    };
    expect(getModelConfigFromAttributes(parsedAttributes)).toEqual({
      modelConfig: {
        modelName: "gpt-3.5-turbo",
        provider: "OPENAI",
        invocationParameters: {},
      },
      parsingErrors: [MODEL_CONFIG_WITH_INVOCATION_PARAMETERS_PARSING_ERROR],
    });
  });
```

### PR DESCRIPTION
**Pull request by cephalization**
resolves #5198
This allows errors to be displayed in the playground UI when the invocation parameters are totally incorrect on the span

image

This is what happens when I set invocation params to "'hi'" in the database

### CODE REVIEW

File: app/src/pages/playground/schemas.ts [hunk 1]
```diff
@@ -136,8 +136,8 @@ const stringToInvocationParametersSchema = z
   .string()
   .transform((s) => {
     const { json } = safelyParseJSON(s);
-    if (json == null) {
-      return {};
+    if (json == null || typeof json !== "object") {
```
Comment (Parker-Stafford) [inline app/src/pages/playground/schemas.ts:139]: i think there might be a isObject in src/typeUtils, don't hafve to use it here though

File: app/src/pages/playground/schemas.ts [hunk 2]
```diff
@@ -156,10 +156,23 @@ const stringToInvocationParametersSchema = z
...
     );
   })
+  .transform((v, ctx) => {
+    const result = invocationParameterSchema.safeParse(v);
+    if (!result.success) {
+      // bubble errors up to the original schema
+      result.error.issues.forEach((issue) => {
+        ctx.addIssue(issue);
+      });
+      // https://zod.dev/?id=validating-during-transform
```
Comment (Parker-Stafford) [inline app/src/pages/playground/schemas.ts:169]: very nice, i figured there was some way to do this but didn't see this, this is awesome

**Review by Parker-Stafford — APPROVED** [review]
