### PR TITLE
fix: Allow scrolling the entire experiment compare table

### LINKED ISSUE #6986: [BUG]: Experiment comparison page doesn't scroll to the bottom
### Where do you use Phoenix

Local (self-hosted)

### What version of Phoenix are you using?

8.21.0

### What operating system are you seeing the problem on?

MacOS

### What version of Python are you running Phoenix with?

Local

### What version of Python or Node are you using instrumentation with?

_No response_

### What instrumentation are you using?

_No response_

### What happened?

The experiment comparison page doesn't let you scroll all the way to the bottom if you have more than a few lines of text in an example.

Gif here: https://drive.google.com/file/d/1Wvu04m6moFdQLH6yCaqpwj0QMJq3s0RA/view?usp=sharing

### What did you expect to happen?

The page to scroll all the way to be able to show the last rows of text.

### How can we reproduce the bug?

Any experiment with multiple lines of output should show it.

Also following the [Prompts UI Quickstart](https://docs.arize.com/phoenix/prompt-engineering/quickstart-prompts/quickstart-prompts-ui) will repro the issue if you look in the experiments comparison view after going through the quickstart

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by cephalization**
Just needed a container around the table segment of the page

### Before

https://github.com/user-attachments/assets/91da0352-9b4e-4d6c-9b35-2ec65ae3fb48

### After

https://github.com/user-attachments/assets/34200be6-0313-4f26-8116-4ad4933af0ed

Resolves #6986

### CODE REVIEW

File: app/src/pages/experiment/ExperimentCompareTable.tsx [hunk 1]
```diff
@@ -456,82 +456,82 @@ export function ExperimentCompareTable(props: ExampleCompareTableProps) {
...
-      </View>
-      <div css={tableWrapCSS}>
-        <table
-          css={css(tableCSS, borderedTableCSS)}
-          style={{
-            ...columnSizeVars,
-            width: table.getTotalSize(),
-            minWidth: "100%",
-          }}
+    <View overflow="auto">
```
Comment (mikeldking) [inline app/src/pages/experiment/ExperimentCompareTable.tsx:460]: strange that the sizing in the table body itself doesn't work here. I might not understand this TBH. Stamping to unblock.

**Review by mikeldking — APPROVED** [review]

File: app/src/pages/experiment/ExperimentCompareTable.tsx (hunk 1 above)
Comment (cephalization) [reply app/src/pages/experiment/ExperimentCompareTable.tsx:460]: Something to do with the filter bar above and the sticky table headers. Not sure the exact root cause to be honest
